### ISSUE TITLE
Ajouter copyright et frame Creative Commons BY-SA au schematics du relay driver

### ISSUE THREAD

**Issue by LoupHC** [LoupHC/controleur-CAPE#14]

**Comment by yoangp** [comment]
Autre chose à rajouter? J'upload la cette version des fichiers KiCad à l'instant.

![image](https://user-images.githubusercontent.com/34359036/34717717-42d26c48-f534-11e7-95b4-d639adb1b1c7.png)

**Comment by LoupHC** [comment]
C'est cute au boute!
Pour les schematics, est-ce que c'est possible d'avoir un frame comme ça (avec la mention de licence)?
[Weather Shield_V12.pdf](https://github.com/LoupHC/controleur-CAPE/files/1615730/Weather.Shield_V12.pdf)

**Comment by LoupHC** [comment]
Salut Yoan!
J'ai fait des logos CAPÉ et creative commons pour ajouter sur nos pcbs, je peux également les ajouter sur le pcb relais.

**Comment by yoangp** [comment]
Salut Loup,

Gêne toi pas si tu veux ajouter cela sur le PCB des relais! :-)

Yoan


2018-02-25 10:16 UTC−05:00, LoupHC <notifications@github.com>:
