### ISSUE TITLE
Doublon dans CAPE_Relay_Shield_V2.zip

### ISSUE THREAD

**Issue by LoupHC** [LoupHC/controleur-CAPE#16]
Deux fichiers .pro?

**Comment by yoangp** [comment]
Je vois qu'un seul fichier .pro dans le fichié zippé...

![image](https://user-images.githubusercontent.com/34359036/34715552-575d107a-f52d-11e7-83de-e7dad668d026.png)

**Comment by LoupHC** [comment]
Heh... ouen efectivement... il s'est juste passé quelque chose dans celui que j'ai downloadé alors...
