### ISSUE TITLE
Soumission PCB motor driver

### ISSUE THREAD

**Issue by LoupHC** [LoupHC/controleur-CAPE#17]

**Comment by yoangp** [comment]
-Est-ce qu'on y va pour PCBWAY?
-Jason, est-ce que tu peux voir si le fournisseur offre que les trous dans le PCB seront plaqués?
-Est-ce que tu peux aussi écrire ici quel grosseur de mèches il est possible d'utiliser pour les trous dans le PCB?

**Comment by jayserf** [comment]
-PCB way ou un tres similaire, je vais comparer 2-3
- Normalement oui. Plated Through Hole (PTH) est standard
-voici les specs complets 
https://www.goldphoenixpcb.com/html/capabilities/rpc.html

https://www.pcbway.com/capabilities.html
