### ISSUE TITLE
Faire routing du contrôleur sur KiCad

### ISSUE THREAD

**Issue by LoupHC** [LoupHC/controleur-CAPE#24]
Ça y est, on rendu là, faire le ménage de tout ce beau bordel :

**Comment by LoupHC** [comment]
![footprints](https://user-images.githubusercontent.com/24371752/34918380-e00f65f8-f91f-11e7-99f1-4864aed2ce3a.png)

**Comment by LoupHC** [comment]
Ça commence à ressembler à qqchose!
![pcb layout](https://user-images.githubusercontent.com/24371752/35241347-2f85e426-ff84-11e7-81b8-7f64f682490a.png)

**Comment by jayserf** [comment]
Fuck yeah! En 3d en plus 🚀

**Comment by LoupHC** [comment]
Yeah, encore plus maintenant!!
![pcb_3d_2](https://user-images.githubusercontent.com/24371752/35305806-e1518a86-0068-11e8-97b8-704d35eca8f8.png)
![pcb_3d](https://user-images.githubusercontent.com/24371752/35305809-e3bd2384-0068-11e8-87ca-32401a0021fb.png)

**Comment by yoangp** [comment]
Coooooooooool!!! :-)

**Comment by LoupHC** [comment]
Guys! I made it!!!!!!!
![0 unconnected](https://user-images.githubusercontent.com/24371752/35352849-484d6bec-0113-11e8-9fe5-222b5f8aa484.png)

**Comment by yoangp** [comment]
Woooowwww! T'as même mis un ground plane! C'est la classe! ;-) Je vais essayer de jetter un coup d'oeil plus approfondi un peu plus tard. Quand prévoies-tu d'envoyer la commande de pcb?

En passant, quand j'ai fait ma commande de pcb, j'ai choisi revètement blanc avec texte noir et pas de plomb dans le revètement. C'était plus cher de prendre sans plomb, mais sans plomb blanc était moins cher que sans plomb vert (!?).

**Comment by LoupHC** [comment]
Je vais réviser 2-3 trucs avant de l'envoyer, réviser toutes les footprints et les largeurs de traces.
Est-ce que Jason tu pourras montrer ça à tes chummys pour avoir leurs commentaires? J'update le fichier Kicad à jour live. 
Je pourrais envoyer ça peut-être d'ici le début de la semaine prochaine? Vendredi si je suis efficace.
Hey pis sont swell en tah les pcb que t'as monté!!!

**Comment by LoupHC** [comment]
Et juste au moment ou je pensais avoir fini.... noooo! J'ai utilisé des connecteur 3.5mm au lieu de 5mm. 
Ça va être un peu plus long que prévu. :P

**Comment by yoangp** [comment]
5.08mm ... ;-)

Moi aussi j'ai fait quelques erreurs comme cela.

Ciao, je te répond aux autres messages ce soir si tout va bien.
Vraiment cool que notre objectif d'inscription soit atteint!

Ciao!

Yoan

2018-01-26 14:35 UTC−05:00, LoupHC <notifications@github.com>:

**Comment by LoupHC** [comment]
Et pour finir en beauté, je me suis permis une petite coqueterie : 
![pcb final](https://user-images.githubusercontent.com/24371752/35468160-9e8b9bd0-02e6-11e8-9818-1ecbe6f9d2c4.png)

**Comment by yoangp** [comment]
C'est trop cute! :)

2018-01-26 22:17 UTC−05:00, LoupHC <notifications@github.com>:

**Comment by jayserf** [comment]
Super nice!
Really like the drawing but that's secondary to the routing!
I'll try to get feedback on Monday so we can send it super quickly

**Comment by jayserf** [comment]
Ignore comments re: SPI connector in other issue. this is good. 
OK now is much clearer to see the board with the real markings and connectors.

J'imagine c'est bon au niveau trous de montage?

**Comment by LoupHC** [comment]
Version finale (on attend les prototypes!) : 
![final version_beta](https://user-images.githubusercontent.com/24371752/35875244-a1aa8ebc-0b3c-11e8-9dfe-31388f2bd34b.png)

**Comment by LoupHC** [comment]
Version finale (après révision) : 
![pcb final top](https://user-images.githubusercontent.com/24371752/36643322-bc53fc32-1a17-11e8-9caa-43fd7d5db20a.png)
![pcb final bottom](https://user-images.githubusercontent.com/24371752/36643323-bd94de22-1a17-11e8-8d42-75b900310563.png)
![3d_view_pcb_controller](https://user-images.githubusercontent.com/24371752/36643324-bfa6072c-1a17-11e8-8c42-686e6163b0eb.png)
