### ISSUE TITLE
Preparer doc pour soumission de PCBA

### ISSUE THREAD

**Issue by jayserf** [LoupHC/controleur-CAPE#26]
Needed info

- Quantities: high & low estimate for **protos** and for **production** orders 
(can put in fab info text file)
- Estimated PCB size (LxW in mm) (can put in fab info text file)
- Boms (one file for each PCB)
        - specify # of TH & SMD parts in each bom
- Fab info:  (see below example from Eagle production pcb) (if you dont know some info its ok, the minimum info needed is the top section)

fabrication_parameters.txt
-------------------------
* 2 layers FR4 
* Finish board thickness 0.7874mm(0.031")
* TOP and BOTTOM copper thickness (1.0oz)
* White solder mask on both side
* Black silkscreen on both side
* HASL finish
* tolerance on drills (3mils)
* minimal drill size (12mils)
* minimal isolation (5mils)
* minimal trace width (5mils)
* PTH vias
* Manufacturer code accepted on PCB
* Tab-Routed panel

CAD Package
-----------
CadSoft EAGLE 5.12 Professionnal 

Gerber files format
-------------------------------------------------
* RS-274X format (Embedded D-Codes)
* 2.4 digits english
* All files are gerber-X format, except drills (.DRILL)
* origin at 0,0

Excellon files format (*.DRILL)
------------------------------------
* Excellon format (Embedded Drill Rack)
* Dimensions 2.4 digits OMIT LEADING ZEROS

included files
---------------
*.DRILL : 	drill file
*.GTL : 	copper layer TOP
*.GBL :  	copper layer BOTTOM
*.GTO : 	silkscreen layer TOP
*.GBO :		silkscreen layer BOTTOM
*.GTS : 	soldermask layer TOP
*.GBS :		soldermask layer BOTTOM
*.GTP :		stencil layer TOP
*.OUT :		board outline layer
*.GD1 :		drill symbol layer
*.MOUNT :	pick and place coordinates
*.png	:	extra pcbs information

**Comment by LoupHC** [comment]
BOM controller components complet!
https://docs.google.com/spreadsheets/d/1U0wZ03mb_SrtCEw6ppra8F-SvSYpekVIvqOV3GDfxJs/edit#gid=0

**Comment by LoupHC** [comment]
J'ai ajouté des détails sur celui des motor drivers aussi.

**Comment by jayserf** [comment]
NIce!

Let me know if you need help with any of the fab stuff

**Comment by jayserf** [comment]
Oui bien sûr je peut envoyer la soumission cet semaine.
Pas aujourd'hui car c'est ma fête mais demain for sure

**Comment by yoangp** [comment]
Bonne fête Jason!!

:-)

Yoan

2018-01-22 15:19 UTC−05:00, jayserf <notifications@github.com>:
> Oui bien sûr je peut envoyer la soumission cet semaine.
> Pas aujourd'hui car c'est ma fête mais demain for sure
>

**Comment by LoupHC** [comment]
Bonne fêteee!!!!!!

**Comment by jayserf** [comment]
thanks guys! I had a good one.

Quotes sent to PCBWay and More-Suns. We'll see what they return and I have some that I know well but definitely charge setup fees so dont want to msg them if we will for sure not use them as they dont specialize in lower volume, but would do a flawless job.
