### ISSUE TITLE
Sondage

### ISSUE THREAD

**Issue by yoangp** [LoupHC/controleur-CAPE#34]
Je vous as ajoutés comme collaborateurs au [formulaire du sondage](https://docs.google.com/forms/d/1WxO17ut5oeYTsKfFmCTYdPt4qe6uDdXuSNXFon4QN1Y/edit) . 

Loup, est-ce que tu veux jetter un dernier coup d'oeil avant qu'on l'envoie? Tu as accès en écriture au besoin. Est-ce que tu t'occupes de l'envoyer aux gens inscrits?

**Comment by LoupHC** [comment]
Oui je m'en occuppe! Merci Yoan!

**Comment by LoupHC** [comment]
C'est envoyé!

**Comment by LoupHC** [comment]
Je vais compiler ici les données du sondage au fur et à mesure que ça rentre : 
https://docs.google.com/spreadsheets/d/1j9LD_4gHe2kkoIPN0RChVHgnP19oJdYkSyDbvr8SMhM/edit#gid=0
En passant, on est sold out!!!! 30 boitiers relais et 25 contrôleurs commandés. Hoppa!!

**Comment by yoangp** [comment]
Malade!! :-)

2018-02-02 10:13 UTC−05:00, LoupHC <notifications@github.com>:
