### ISSUE TITLE
OUFFFFF.... sockets de relais

### ISSUE THREAD

**Issue by LoupHC** [LoupHC/controleur-CAPE#37]
Merde les gars, je crois que je viens de nous éviter un fail monumental.
J'ai commandé hier des sockets de relais through hole parceque je monte un boitier relais pour un gars... bien figurez-vous que les pins sont pas en face des trous.
Hier, j'ai aussi envoyé la soumission d'assemblage des Pcbs.
C'est comme qui dirait.... un bon timing.

**Comment by yoangp** [comment]
Allo Loup! Bien vu! Mais je croyais que tu avais acheté déjà ces sockets pour les drivers de moteurs que tu as monté chez toi!?! J'avais trafiqué mes sockets de relais à partir d'un modèle différent car c'était back-order au moment que j'ai fait le montage, donc je n'ai jamais eu la vrai pièce... Quel est le numéro Digikey de la pièce que tu as commandé et qui ne fitte pas? Est-ce que tu peux me dire quelle dimension n'est pas bonne sur le footprint?
