### ISSUE TITLE
Documents techniques

### ISSUE THREAD

**Issue by LoupHC** [LoupHC/controleur-CAPE#41]
Ceci est une ébauche concernant les documents techniques à produire pour l'atelier. 
J'en ai fait 4 aujourd'hui que je vous présente, et qui m'on permis de commencer à définir une terminologie qu'on pourrait utiliser pour se comprendre à l'atelier.

**Comment by LoupHC** [comment]
Premier document, l'assemblage des connecteurs sur le boitier. La terminologie utilisée ici : 
- les connecteurs sont numérotés de C1  à C14 un peu comme les pins d'une chip électronique, en partant d'en haut à gauche, en descendant et en remontant par la droite.
- un M veut dire connecteur mâle et un F connecteur femelle
- en plus du numéro de connecteur, chaque pin est numérotée, donc si on parle de la pin 3 du connecteur #4 on dira C4-3, etc.
- les relais sont numérotés de 1 à 3 et chaque pins sont numérotées de 1-8, donc la pin 6 du relais 3 = relais3-6
- pour le reste, j'ai utilisé les inscriptions marquées sur les pcbs
![tutoriel0004](https://user-images.githubusercontent.com/24371752/38591756-594aa4da-3d06-11e8-9b43-7f82b248d706.jpeg)

**Comment by LoupHC** [comment]
Deuxième document, l'assemblage des switchs d'override sur la porte.
- Ici, les switchs d'override sont numérotées de  S1 à S6 dans le sens de la lecture (gauche-droite/haut-bas)
- Sauf la switch d'alarme, qui s'appelle ALARM-S
- Le bouton d'urgence s'appelle STOP(vis : STOP-IN et STOP-OUT)
![tutoriel0005](https://user-images.githubusercontent.com/24371752/38591881-03b9d544-3d07-11e8-9127-4679a8589311.jpeg)

**Comment by LoupHC** [comment]
Et voici deux tutoriels : un pour l'assemblage de la sonde et un pour l'assemblage de l'interface.
![tutoriel0001](https://user-images.githubusercontent.com/24371752/38591904-2e27e0a0-3d07-11e8-88b7-46a0bef58257.jpeg)
![tutoriel0002](https://user-images.githubusercontent.com/24371752/38591908-300d4162-3d07-11e8-918e-12fb0f8f4748.jpeg)
![tutoriel0003](https://user-images.githubusercontent.com/24371752/38591909-31dc751c-3d07-11e8-9e6c-6397c70c09ec.jpeg)

**Comment by LoupHC** [comment]
Voici ce que je pense faire d'ici l'atelier en plus de ça : 
- longueurs et couleur des câbles
- tableau résumant les connexions (comme ce que t'avais fait Yoan en 2016)
Avez-vous d'autres suggestions de documents à faire?

**Comment by jayserf** [comment]
Il faut que j'y pense plus...

**Comment by LoupHC** [comment]
Document sur la longueur des fils : 
[Longueurs de fil.docx](https://github.com/LoupHC/controleur-CAPE/files/1900225/Longueurs.de.fil.docx)

**Comment by yoangp** [comment]
Wow, great job Loup!

2018-04-11 15:33 GMT-04:00 LoupHC <notifications@github.com>:

**Comment by jayserf** [comment]
Vraiment! Travaille de fou

**Comment by yoangp** [comment]
Document en cours sur les étapes de montage:
https://docs.google.com/spreadsheets/d/1Ph90L6zSw53EDh-UzOvEIbaZvkrDvfvorQicZrnXrpg/edit#gid=0
