### ISSUE TITLE
Câbles à acheter

### ISSUE THREAD

**Issue by LoupHC** [LoupHC/controleur-CAPE#42]
Il nous manque  : 
du fil blanc 1-cond 18AWG (300 pieds environ)
du fil noir 1-cond 18AWG (100 pieds environ)

**Comment by yoangp** [comment]
Ok, je vais aller chercher cela chez Addison!

2018-04-11 15:28 GMT-04:00 LoupHC <notifications@github.com>:

**Comment by jayserf** [comment]
10-4 merci Yoan

**Comment by yoangp** [comment]
J'ai ça!

**Comment by jayserf** [comment]
Nice!
