### ISSUE TITLE
Bug :  stages identiques

### ISSUE THREAD

**Issue by LoupHC** [LoupHC/controleur-CAPE#53]
Rapport de bug de Fred Verville
"Ah oui, pour le côté ouvrant qui ne fermait pas le soir, j'ai (re)trouvé le problème. C'est parce que mes deux derniers "stage" d'ouverture était le même, soit 100%. Ça fait buger le contrôleur de passer d'un stade à un autre avec un même niveau d'ouverture, ça m'était arrivé sur ma 1ère serre aussi, avec deux niveaux d'ouverture d'un côté à 0% pour les deux premiers stages. Bref, pour que tout fonctionne, faut toujours qu'il y ait un petit changement de l'ouverture d'un stage à l'autre, même si c'est 2%. Bref, je sais pas si tu étais au courant mais je te le dis! :P
"

**Comment by yoangp** [comment]
Bon à savoir et important à corriger dans la prochaine version du code!
