### ISSUE TITLE
Manque librairie pour schéma KiCAD

### ISSUE THREAD

**Issue by yoangp** [LoupHC/controleur-CAPE#63]
Loup,

Il manque une librairie dans les fichiers KiCAD (image ci-dessous), est-ce que tu pourrais l'ajouter dans les fichiers KiCAD sur GitHub?

![image](https://user-images.githubusercontent.com/34359036/51291223-69c83380-19d4-11e9-9e05-22fbd5cea4d8.png)

**Comment by LoupHC** [comment]
Snaps... je me mets là dessus

**Comment by LoupHC** [comment]
C'est bizarre... il me dit qu'il manque les librairies, mais en vrai il arrive à ouvrir le fichier quand même...

**Comment by LoupHC** [comment]
Shit je pense qu'ils ont changé le système de librairies pour les footprints... par une méthode plus compliquée qu'avant... mais les fichiers sont encore là.
Je vais les archiver sur github ça va être plus simple à l'avenir.

**Comment by LoupHC** [comment]
J'ai mis à jour KiCad (passé de 4.0 à 5.0) et maintenant j'ai plus de problème avec les footprints. Par contre, c'est plus compatible avec KiCad 4.0...
J'ai reploadé ça dans une branche à part : KiCad-edit-2019
On pourrait mettre nos modifications là-dessus en attendant d'avoir qqchose qui vaut la peine d'être updaté!
Si tu mets à jour ta version est-ce que ça te pose encore problème?

**Comment by yoangp** [comment]
Cool! Résolu de mon côté aussi avec KiCAD V5 et la version mise à jour du projet (KiCad-edit-2019)
