### ISSUE TITLE
Décision Relais sur PCB ou rail DIN

### ISSUE THREAD

**Issue by LoupHC** [LoupHC/controleur-CAPE#8]
Assemblage sur Din rail(relais et contrôleur)
Pour : 
- modulaire
- plus facilement hackable
- intérêt pédagogique à faire un peu soi-même son filage
Contre : 
- plus de filage à faire à la main

Au niveau matériel, on pourrait utiliser ces racks-là pour les motor driver:
https://www.aliexpress.com/item/UM122-PCB-length-51-100mm-profile-panel-mounting-base-PCB-housing-PCB-din-rail-PCB-carrier/32622345793.html?spm=2114.search0104.3.123.VToMou&ws_ab_test=searchweb0_0,searchweb201602_5_10152_10151_10065_10130_10068_10344_10547_10342_10343_10340_10548_10341_10084_10083_10139_10307_10059_10314_10534_100031_10604_10103_10142,searchweb201603_25,ppcSwitch_5&algo_expid=6f677fa1-1931-41cc-8b40-aa9abdb1fa74-18&algo_pvid=6f677fa1-1931-41cc-8b40-aa9abdb1fa74&priceBeautifyAB=0
ou ceux-là, plus cheaps :
https://www.aliexpress.com/item/OOTDTY-PCB-35mm-DIN-Rail-Mounting-Adapter-Circuit-Board-Bracket-Holder-Carrier-Clips/32839808362.html?spm=2114.search0104.3.9.VToMou&ws_ab_test=searchweb0_0,searchweb201602_5_10152_10151_10065_10130_10068_10344_10547_10342_10343_10340_10548_10341_10084_10083_10139_10307_10059_10314_10534_100031_10604_10103_10142,searchweb201603_25,ppcSwitch_5&algo_expid=6f677fa1-1931-41cc-8b40-aa9abdb1fa74-1&algo_pvid=6f677fa1-1931-41cc-8b40-aa9abdb1fa74&priceBeautifyAB=0
On pourrait même monter le contrôleur dans un boitier comme ça : 
https://www.okwenclosures.com/en/Railtec-B/B6506115.htm

Assemblage sur PCB (relais)
Pour :
- divise en 2 le filage
- choix de pièces illimité
Contre :
- pas autant modulable/hackable
- on est short dans le temps pour designer nos PCBs

**Comment by yoangp** [comment]
Sur PCB avec supports DIN pour PCB: https://www.aliexpress.com/item/OOTDTY-PCB-35mm-DIN-Rail-Mounting-Adapter-Circuit-Board-Bracket-Holder-Carrier-Clips/32839808362.html?spm=2114.search0104.3.9.VToMou&ws_ab_test=searchweb0_0,searchweb201602_5_10152_10151_10065_10130_10068_10344_10547_10342_10343_10340_10548_10341_10084_10083_10139_10307_10059_10314_10534_100031_10604_10103_10142,searchweb201603_25,ppcSwitch_5&algo_expid=6f677fa1-1931-41cc-8b40-aa9abdb1fa74-1&algo_pvid=6f677fa1-1931-41cc-8b40-aa9abdb1fa74&priceBeautifyAB=0
